"""
Jesse Rule Significance Test Service Functions

Mirrors the structure of the backtest service module so the MCP agent can stage
and run rule significance tests the same way it stages and runs backtests.

Endpoints used (all under /significance-test):
    POST /update-state                          create or update a draft
    POST /sessions/{id}                         retrieve one session
    POST /sessions                              list sessions
    POST /sessions/{id}/notes                   update notes / strategy code
    POST                                        start the significance test
    POST /cancel                                cancel a running test
    POST /purge-sessions                        delete old sessions
"""

import json
import os
import uuid
import requests
from typing import Optional

import jesse.mcp.mcp_config as mcp_config
from .auth import hash_password


DEFAULT_SIG_TEST_CONFIG = {
    'warm_up_candles': 210,
    'exchange': {
        'balance': 10_000,
        'fee': 0.0006,
        'type': 'futures',
        'futures_leverage': 1,
        'futures_leverage_mode': 'cross',
    },
}


def _build_default_title(routes_list: list) -> str:
    if routes_list:
        first_route = routes_list[0]
        if isinstance(first_route, dict):
            symbol = first_route.get('symbol') or 'Unknown Symbol'
            timeframe = first_route.get('timeframe') or 'Unknown Timeframe'
            strategy = first_route.get('strategy') or 'Unknown Strategy'
            return f"MCP Rule Significance Test: {strategy} on {symbol} {timeframe}"
    return "MCP Rule Significance Test"


def _normalize_title(title: str) -> str:
    title = title.strip() if title else "MCP Rule Significance Test"
    lowered = title.lower()
    if "mcp" in lowered and "significance" in lowered:
        return title
    return f"MCP Rule Significance Test: {title}"


def _build_default_description(
    exchange: str,
    routes_list: list,
    start_date: str,
    finish_date: str,
    n_simulations: int,
    random_seed: Optional[int],
    strategy_summary: Optional[str],
    hypothesis: Optional[str],
    rationale: Optional[str],
) -> str:
    first = routes_list[0] if routes_list else {}
    strategy_default = (
        f"`{first.get('strategy', 'Unknown')}` on `{first.get('symbol', 'unknown')}` "
        f"using the `{first.get('timeframe', 'unknown')}` timeframe."
    )
    summary_lines = [
        f"- **Strategy:** {strategy_summary or strategy_default}",
    ]
    if hypothesis:
        summary_lines.append(f"- **Hypothesis:** {hypothesis}")
    if rationale:
        summary_lines.append(f"- **Rationale:** {rationale}")
    summary_lines.extend([
        f"- **Period:** `{start_date}` to `{finish_date}`",
        f"- **Exchange:** `{exchange}`",
        f"- **Simulations:** {n_simulations}",
        f"- **Random seed:** {'fixed' if random_seed is not None else 'auto'}",
    ])
    summary_text = "\n".join(summary_lines)
    return (
        "## MCP Rule Significance Test Notes\n\n"
        "Generated by **Jesse MCP**.\n\n"
        "### Summary\n\n"
        f"{summary_text}"
    )


def _collect_strategy_codes(routes_list: list) -> dict:
    strategy_codes = {}
    for route in routes_list:
        if not isinstance(route, dict):
            continue
        exchange = route.get('exchange')
        symbol = route.get('symbol')
        strategy = route.get('strategy')
        if not exchange or not symbol or not strategy:
            continue
        key = f"{exchange}-{symbol}"
        if key in strategy_codes:
            continue
        path = os.path.join('strategies', strategy, '__init__.py')
        try:
            if os.path.exists(path):
                with open(path, 'r', encoding='utf-8') as f:
                    strategy_codes[key] = f.read()
        except Exception:
            pass
    return strategy_codes


def _post_notes(api_url: str, auth: str, session_id: str, title: Optional[str],
                description: Optional[str], strategy_codes: Optional[dict]) -> dict:
    payload = {
        'id': session_id,
        'title': title,
        'description': description,
        'strategy_codes': strategy_codes,
    }
    response = requests.post(
        f'{api_url}/significance-test/sessions/{session_id}/notes',
        json=payload,
        headers={'Authorization': auth},
        timeout=10,
    )
    if response.status_code == 200:
        return {'status': 'success', 'message': 'Notes updated'}
    if response.status_code == 401:
        return {'status': 'error', 'message': 'Authentication failed'}
    if response.status_code == 404:
        return {'status': 'error', 'message': f'Session {session_id} not found'}
    return {'status': 'error', 'message': f'Failed to update notes: {response.text}'}


def create_significance_test_draft_service(
    exchange: str = "Binance Perpetual Futures",
    routes: str = '[{"exchange": "Binance Perpetual Futures", "strategy": "ExampleStrategy", "symbol": "BTC-USDT", "timeframe": "4h"}]',
    data_routes: str = '[]',
    start_date: str = "2021-01-01",
    finish_date: str = "2022-01-01",
    n_simulations: int = 2000,
    random_seed: Optional[int] = None,
    title: Optional[str] = None,
    description: Optional[str] = None,
    strategy_summary: Optional[str] = None,
    hypothesis: Optional[str] = None,
    rationale: Optional[str] = None,
) -> dict:
    api_url = mcp_config.JESSE_API_URL
    password = mcp_config.JESSE_PASSWORD

    try:
        auth = hash_password(password)
        session_id = str(uuid.uuid4())

        try:
            routes_list = json.loads(routes)
            data_routes_list = json.loads(data_routes)
        except json.JSONDecodeError as e:
            return {'status': 'error', 'message': 'Invalid JSON for routes/data_routes', 'details': str(e)}

        if not isinstance(routes_list, list) or not isinstance(data_routes_list, list):
            return {'status': 'error', 'message': 'routes and data_routes must be JSON arrays'}

        if len(routes_list) != 1:
            return {'status': 'error', 'message': 'Rule Significance Test requires exactly one trading route.'}

        form_data = {
            'id': session_id,
            'exchange': exchange,
            'routes': routes_list,
            'data_routes': data_routes_list,
            'start_date': start_date,
            'finish_date': finish_date,
            'n_simulations': int(n_simulations),
            'random_seed': int(random_seed) if random_seed is not None else None,
        }

        state_dict = {
            'form': form_data,
            'results': {
                'alert': {'message': '', 'type': ''},
            },
        }

        response = requests.post(
            f'{api_url}/significance-test/update-state',
            json={'id': session_id, 'state': state_dict},
            headers={'Authorization': auth},
            timeout=10,
        )

        if response.status_code == 401:
            return {'status': 'error', 'message': 'Authentication failed'}
        if response.status_code != 200:
            return {'status': 'error', 'message': f'Failed to persist draft: {response.text}'}

        note_title = _normalize_title(title or _build_default_title(routes_list))
        note_description = description or _build_default_description(
            exchange=exchange,
            routes_list=routes_list,
            start_date=start_date,
            finish_date=finish_date,
            n_simulations=int(n_simulations),
            random_seed=random_seed,
            strategy_summary=strategy_summary,
            hypothesis=hypothesis,
            rationale=rationale,
        )
        strategy_codes = _collect_strategy_codes(routes_list)
        notes_result = _post_notes(
            api_url=api_url,
            auth=auth,
            session_id=session_id,
            title=note_title,
            description=note_description,
            strategy_codes=strategy_codes or None,
        )

        result = {
            'status': 'success',
            'session_id': session_id,
            'draft_state': state_dict,
            'notes': {
                'title': note_title,
                'description': note_description,
                'strategy_code_keys': list(strategy_codes.keys()),
                'strategy_codes_captured': len(strategy_codes),
            },
            'dashboard_url': mcp_config.dashboard_url('significance_test', session_id),
            'message': f'Significance test draft created with ID: {session_id}',
        }
        if notes_result.get('status') != 'success':
            result['warning'] = notes_result.get('message')
        return result

    except requests.exceptions.RequestException as e:
        return {'status': 'error', 'error': str(e), 'message': 'Failed to connect to Jesse API'}
    except Exception as e:
        return {'status': 'error', 'error': str(e), 'message': 'Failed to create significance test draft'}


def update_significance_test_draft_service(session_id: str, state: str) -> dict:
    api_url = mcp_config.JESSE_API_URL
    password = mcp_config.JESSE_PASSWORD

    try:
        auth = hash_password(password)
        state_dict = json.loads(state)

        response = requests.post(
            f'{api_url}/significance-test/update-state',
            json={'id': session_id, 'state': state_dict},
            headers={'Authorization': auth},
            timeout=10,
        )

        if response.status_code == 200:
            return {
                'status': 'success',
                'session_id': session_id,
                'draft_state': state_dict,
                'message': 'Significance test draft updated successfully',
            }
        if response.status_code == 401:
            return {'status': 'error', 'message': 'Authentication failed'}
        return {'status': 'error', 'message': f'Failed to update draft: {response.text}'}

    except json.JSONDecodeError as e:
        return {'status': 'error', 'error': 'Invalid JSON format', 'details': str(e),
                'message': 'Failed to parse state JSON'}
    except requests.exceptions.RequestException as e:
        return {'status': 'error', 'error': str(e), 'message': 'Failed to connect to Jesse API'}
    except Exception as e:
        return {'status': 'error', 'error': str(e), 'message': 'Failed to update significance test draft'}


def update_significance_test_notes_service(
    session_id: str,
    title: Optional[str] = None,
    description: Optional[str] = None,
    strategy_codes: Optional[str] = None,
) -> dict:
    api_url = mcp_config.JESSE_API_URL
    password = mcp_config.JESSE_PASSWORD

    try:
        auth = hash_password(password)
        parsed_codes = None
        if strategy_codes is not None:
            parsed_codes = json.loads(strategy_codes)
            if not isinstance(parsed_codes, dict):
                return {'status': 'error', 'message': 'strategy_codes must be a JSON object string'}

        result = _post_notes(api_url, auth, session_id, title, description, parsed_codes)
        if result.get('status') == 'success':
            return {
                'status': 'success',
                'session_id': session_id,
                'title': title,
                'description': description,
                'strategy_code_keys': list(parsed_codes.keys()) if parsed_codes else [],
                'strategy_codes_captured': len(parsed_codes) if parsed_codes else 0,
                'message': 'Significance test session notes updated successfully',
            }
        return result

    except json.JSONDecodeError as e:
        return {'status': 'error', 'error': 'Invalid JSON format', 'details': str(e),
                'message': 'Failed to parse strategy_codes JSON'}
    except requests.exceptions.RequestException as e:
        return {'status': 'error', 'error': str(e), 'message': 'Failed to connect to Jesse API'}
    except Exception as e:
        return {'status': 'error', 'error': str(e), 'message': 'Failed to update significance test notes'}


def get_significance_test_session_service(session_id: str) -> dict:
    api_url = mcp_config.JESSE_API_URL
    password = mcp_config.JESSE_PASSWORD

    try:
        auth = hash_password(password)
        response = requests.post(
            f'{api_url}/significance-test/sessions/{session_id}',
            headers={'Authorization': auth},
            timeout=10,
        )
        if response.status_code == 200:
            data = response.json()
            return {
                'data': {'session': data.get('session', {})},
                'dashboard_url': mcp_config.dashboard_url('significance_test', session_id),
                'error': None,
                'message': 'Significance test session retrieved successfully',
            }
        if response.status_code == 404:
            return {'data': None, 'error': f'Session {session_id} not found',
                    'message': f'Session {session_id} not found'}
        if response.status_code == 401:
            return {'data': None, 'error': 'Authentication failed', 'message': 'Authentication failed'}
        return {'data': None, 'error': f'Failed to retrieve session: {response.text}',
                'message': f'Failed to retrieve session: {response.text}'}

    except requests.exceptions.RequestException as e:
        return {'data': None, 'error': f'Failed to connect to Jesse API: {str(e)}',
                'message': f'Failed to connect to Jesse API: {str(e)}'}
    except Exception as e:
        return {'data': None, 'error': f'Failed to retrieve session: {str(e)}',
                'message': f'Failed to retrieve session: {str(e)}'}


def get_significance_test_sessions_service(
    limit: int = 50,
    offset: int = 0,
    title_search: Optional[str] = None,
    status_filter: Optional[str] = None,
    date_filter: Optional[str] = None,
) -> dict:
    api_url = mcp_config.JESSE_API_URL
    password = mcp_config.JESSE_PASSWORD

    try:
        auth = hash_password(password)
        payload = {
            'limit': int(limit),
            'offset': int(offset),
            'title_search': title_search,
            'status_filter': status_filter,
            'date_filter': date_filter,
        }
        response = requests.post(
            f'{api_url}/significance-test/sessions',
            json=payload,
            headers={'Authorization': auth},
            timeout=10,
        )
        if response.status_code == 200:
            data = response.json()
            return {
                'status': 'success',
                'sessions': data.get('sessions', []),
                'count': data.get('count', 0),
                'message': f'Retrieved {data.get("count", 0)} significance test session(s)',
            }
        if response.status_code == 401:
            return {'status': 'error', 'message': 'Authentication failed'}
        return {'status': 'error', 'message': f'Failed to retrieve sessions: {response.text}'}

    except requests.exceptions.RequestException as e:
        return {'status': 'error', 'error': str(e), 'message': 'Failed to connect to Jesse API'}
    except Exception as e:
        return {'status': 'error', 'error': str(e), 'message': 'Failed to retrieve significance test sessions'}


def run_significance_test_service(session_id: str) -> dict:
    api_url = mcp_config.JESSE_API_URL
    password = mcp_config.JESSE_PASSWORD

    try:
        auth = hash_password(password)

        session_response = requests.post(
            f'{api_url}/significance-test/sessions/{session_id}',
            headers={'Authorization': auth},
            timeout=10,
        )

        if session_response.status_code == 404:
            return {'status': 'error', 'message': f'Session {session_id} not found'}
        if session_response.status_code == 401:
            return {'status': 'error', 'message': 'Authentication failed'}
        if session_response.status_code != 200:
            return {'status': 'error', 'message': f'Failed to retrieve session: {session_response.text}'}

        session_data = session_response.json()
        session = session_data.get('session', {})
        state = session.get('state')
        form = state.get('form') if isinstance(state, dict) else None
        if isinstance(form, str):
            form = json.loads(form)

        if not form:
            return {
                'status': 'error',
                'message': 'No form found in session state. Create a draft first using create_significance_test_draft.',
            }

        routes_list = form.get('routes', [])
        if len(routes_list) != 1:
            return {'status': 'error', 'message': 'Rule Significance Test requires exactly one trading route.'}

        payload = {
            'id': session_id,
            'exchange': form.get('exchange'),
            'routes': routes_list,
            'data_routes': form.get('data_routes', []),
            'config': DEFAULT_SIG_TEST_CONFIG,
            'start_date': form.get('start_date'),
            'finish_date': form.get('finish_date'),
            'n_simulations': int(form.get('n_simulations', 2000)),
            'random_seed': form.get('random_seed'),
            'theme': 'light',
            'state': state if isinstance(state, dict) else {},
        }

        response = requests.post(
            f'{api_url}/significance-test',
            json=payload,
            headers={'Authorization': auth},
            timeout=10,
        )

        if response.status_code == 202:
            return {
                'status': 'started',
                'session_id': session_id,
                'dashboard_url': mcp_config.dashboard_url('significance_test', session_id),
                'message': (
                    'Rule significance test started. '
                    'Poll get_significance_test_session(session_id) until status is "finished".'
                ),
            }
        if response.status_code == 401:
            return {'status': 'error', 'message': 'Authentication failed'}
        if response.status_code == 409:
            return {'status': 'error', 'message': f'Session {session_id} is already running or completed.'}
        return {'status': 'error', 'message': f'Failed to start significance test: {response.text}'}

    except requests.exceptions.RequestException as e:
        return {'status': 'error', 'error': str(e), 'message': 'Failed to connect to Jesse API'}
    except Exception as e:
        return {'status': 'error', 'error': str(e), 'message': 'Failed to run significance test'}


def cancel_significance_test_service(session_id: str) -> dict:
    api_url = mcp_config.JESSE_API_URL
    password = mcp_config.JESSE_PASSWORD

    try:
        auth = hash_password(password)
        response = requests.post(
            f'{api_url}/significance-test/cancel',
            json={'id': session_id},
            headers={'Authorization': auth},
            timeout=10,
        )
        if response.status_code == 202:
            return {'status': 'success', 'session_id': session_id,
                    'message': f'Significance test {session_id} cancellation requested'}
        if response.status_code == 401:
            return {'status': 'error', 'message': 'Authentication failed'}
        return {'status': 'error', 'message': f'Failed to cancel: {response.text}'}

    except requests.exceptions.RequestException as e:
        return {'status': 'error', 'error': str(e), 'message': 'Failed to connect to Jesse API'}
    except Exception as e:
        return {'status': 'error', 'error': str(e), 'message': 'Failed to cancel significance test'}


def purge_significance_test_sessions_service(days_old: Optional[int] = None) -> dict:
    api_url = mcp_config.JESSE_API_URL
    password = mcp_config.JESSE_PASSWORD

    try:
        auth = hash_password(password)
        payload = {'days_old': days_old}
        response = requests.post(
            f'{api_url}/significance-test/purge-sessions',
            json=payload,
            headers={'Authorization': auth},
            timeout=10,
        )
        if response.status_code == 200:
            data = response.json()
            deleted_count = data.get('deleted_count', 0)
            return {
                'status': 'success',
                'deleted_count': deleted_count,
                'message': f'Successfully purged {deleted_count} significance test session(s)',
            }
        if response.status_code == 401:
            return {'status': 'error', 'message': 'Authentication failed'}
        return {'status': 'error', 'message': f'Failed to purge sessions: {response.text}'}

    except requests.exceptions.RequestException as e:
        return {'status': 'error', 'error': str(e), 'message': 'Failed to connect to Jesse API'}
    except Exception as e:
        return {'status': 'error', 'error': str(e), 'message': 'Failed to purge significance test sessions'}
